### PR TITLE
feat: use Type.icon, create icon inclusion tag

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

This PR:

- Adopts `Type.icon` as seen in #111.
- Creates a Django [inclusion tag](https://docs.djangoproject.com/en/3.0/howto/custom-template-tags/#inclusion-tags) for generating SVG icon markup.

## Steps to test

1. Check out pull request.
2. Visit "My profiles" and a sample of organization and individual profile pages.

**Expected behavior:** All SVG icons load as expected.

## Additional information

Not applicable.

## Related issues

Blocked by #111.

### CODE REVIEW

**Comment by erictheise** [comment]
Would be helpful to have a comprehensive visual of all icons being introduced.

**Comment by greatislander** [comment]
@erictheise These are shown here: https://pinecone.platform.coop/components/preview/icons

**Comment by greatislander** [comment]
I can update that page in Pinecone to show the icon names for easy reference.

**Comment by erictheise** [comment]
Think I read the ticket too soon after #111 and misread it being about verifying icons for 

* Cooperative
* Potential cooperative
* Shared platform
* Supporting organization

which I have not seen.

**Comment by greatislander** [comment]
Ah, yeah, those are not yet implemented. This will support them once they are added to the Types data model.

**Pull request merged**
