### PR TITLE
feat: add 'made by a cooperative' field to tools model

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

This PR adds a new choices field, `coop_made`, to the Tools model, which indicates whether or not the tool was made by a cooperative.

## Steps to test

1. Run migrations.
2. Edit a tool from the admin.
3. Visit the tools API endpoint.

**Expected behavior:** In the tool editing interface, a checkbox for "Made by a cooperative" appears. In the API, the `coop_made` attribute appears as `false` if not set, or one of the following if set:

- `unknown`
- `yes`
- `no`

## Additional information

Not applicable.

## Related issues

Not applicable.

### CODE REVIEW

**Comment by erictheise** [comment]
@greatislander, I've got a few issues with this one.

- could you break it into two pull requests, one for `coop_made`, one for dropping `sectors`? You'll need to rollback your database with `./manage.py migrate mdi 0068` then delete this `0069`.
- the way Django works it's a bad idea to allow `null` in text fields but for numbers and Booleans, it's okay. Consider creating `coop_made` with `default=False, null=True` to allow for cases where it's unknown if the tool is made by a coop. You may see reference to `NullBooleanField` but it's on its way out so don't use that.
- I've not been consistent about this myself but it's good practice to name the migration when you create it, e.g., `./manage.py makemigrations mdi add_coop_made` or somesuch.
- I'll keep my `sectors` questions for that PR.

Thanks.

**Comment by greatislander** [comment]
@erictheise Updated.

**Comment by erictheise** [comment]
Apologies, @greatislander, I don't know what happened between my brain and my fingers (my seized up shoulders, TBH) but I meant to type `default=True, null=True` above. Users adding a tool may not know about the tool's creation history and I don't think we should default to __Not made by a cooperative__.

I am going to accept and run this migration, then add another with `default=True` to this issue if you agree.

**Comment by greatislander** [comment]
@erictheise I actually have kind of an opposite concern, which is that users may accidentally imply that tools are created by co-ops when they aren’t (as far as I’m aware, only Loomio is among our current list of tools. It might be better in this instance to offer three options with the default being “I don’t know” or something similar. Thoughts?

**Comment by greatislander** [comment]
@dayotte @cherylhjli Also let me know what you think if you see this before we figure it out and merge.

**Comment by erictheise** [comment]
Makes sense to me @greatislander. You could implement that triad using `choices=` as with `Organization.geo_scope` or `.code_availability`. __Not sure__ seems like good wording.

**Comment by erictheise** [comment]
@greatislander, this pull request [still drops `sectors` from serializers.py](https://github.com/platform-coop-toolkit/coop-map-directory-index/pull/59#pullrequestreview-417901588) when it should be part of #62.

**Comment by greatislander** [comment]
Fixed @erictheise.

**Comment by greatislander** [comment]
@erictheise I restored sectors in https://github.com/platform-coop-toolkit/coop-map-directory-index/pull/59/commits/c89e8a134c18c6da905e4ac16e832d2b892e5d22. Am I missing something?

**Comment by erictheise** [comment]
Probably I'm missing something @greatislander, the GitHub diff showed

`    sectors = serializers.StringRelatedField(many=True)`

as being having been removed but I see it's there. Will stick to my IDE.

**Comment by greatislander** [comment]
Probably was the earlier commit showing. Thanks!

**Pull request merged**
