### PR TITLE
Geocoding steps

### PR DESCRIPTION
**Pull request by erictheise**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

This PR adds a `geolocation` step after the `contact_info` step in both the individual and organization profile flow.

## Steps to test

1. Initiate individual profile creation
2. Verify a map appears at the third step
3. Adjust the location or not
4. Continue to end of profile creation
5. Verify the same location appears in the `/admin` interface for that `User`
6. Initiate organization profile creation
7. Verify a map appears at the third step
8. Adjust the location or not
9. Continue to end of profile creation
10. For a change of pace to the homepage and verify that the new `Organization` appears where expected on the map

**Expected behavior:** 

## Additional information

Outstanding issues:
* there is a hack to pull `lng` & `lat` into hidden fields that are immediately copied to other hidden fields. Something is incorrect in the form `context`.
* I've done nothing to make the crosshairs redraw if the map dimensions change.
* the use of the Mapbox `light` style is a placeholder to differentiate from the homepage map.

## Related issues

I considered this part of #6 & #7 but the emphasis of those issues evolved. This deals with complete

### CODE REVIEW

**Comment by erictheise** [comment]
Go for it re: copy/styling changes, @greatislander. This was the first feature I asked for design help on but I've never seen a mockup for it. Strongly suggest not losing the crosshairs as I've always found ambiguity about where the `Point` is with the more common implementation of dragging a teardrop-shaped map marker.

Is it the dot at the center of the teardrop? (no, but that calls attention to itself)
Is it the exact tip of the teardrop? Should there be a few pixels of whitespace between the tip and the point?

I believe crosshairs remove that ambiguity.

**Comment by erictheise** [comment]
I'd like to take another look at the `context` issue with fresh eyes but if you get to it first, go for that, too.

**Comment by greatislander** [comment]
@erictheise This is what I'm working with from Figma. Agree on the crosshairs. Will adjust copy to reflect that the point is the center as opposed to the pin location.

Screen Shot 2020-06-25 at 11 16 26 AM

**Comment by erictheise** [comment]
Teardrops are fine for display but not so great for setting locations. Also, they are not [pins](http://mobile-radio.net/test/radia_map.html). Actual pin icons with drop shadows that converge at the tip, simulating when a pin descends from the sky to the ground are an improvement because they have a finer point and depth cues but crosshairs are minimal, lightweight, and even more direct.

**Comment by greatislander** [comment]
@erictheise Ready for review. Crosshairs update with map resizing, and I've set up the forms to initialize with the fields pre-populated with latitude and longitude.

**Comment by erictheise** [comment]
Crosshairs redraw does not seem to fully work when expanding or contracting horizontally on desktop. Center is maintained but the right horizontal bar does not recover at all widths.

image

image

**Comment by erictheise** [comment]
Going wide breaks around 1920 pixels. Going narrow breaks around 960px. On Chrome OSX.

**Comment by greatislander** [comment]
@erictheise Good catch. Just pushed a fix.

**Comment by erictheise** [comment]
* at Page 3 of 7 set your screen for 1024 x 1024
* proceed to Page 4.
* crosshairs still break widening past 1920, shrinking from here below 960 break again
* same behavior shrinking first, then widening

**Comment by greatislander** [comment]
@erictheise I merged dev into this branch, then ran `npm ci` and `npm run dev`. I can't reproduce the issue. Can you pull the latest commit and check again?

**Comment by erictheise** [comment]
Just did, whatever came in from `dev` seems to have fixed it.

**Pull request merged**
