### PR TITLE
feat: individual and organization profile creation flows

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Improves individual profile creation flow:

- [x] Basic information
- [x] Contact information
- [x] Describe your role
- [x] More about you
- [x] Detailed information
- [x] Social media

Adds organization profile creation flow:

- [x] Basic information
- [x] Contact information
- [x] Detailed information
	- [x] Date founded
- [x] Scope and impact
	- [x] Geographic scope
	- [x] Numbers impacted
- [x] Social media

Additionally:

- [x] Skips "More about you" if only "Other" role was selected
- [x] Properly handles division of `Organization.category` choices depending on type selection.
- [x] Handles organization profile creation
	- [x] Redirects to profile page on creation

Outstanding bugs:

- [x] Cannot use multiple select for `User.member_of`, `User.founder_of`, `User.worked_with`
- [x] Cannot select `Organization.geo_scope`

## Steps to test

1. Fully test individual profile creation flow.
2. Fully test organization profile creation flow.

## Additional information

Not applicable.

## Related issues

- Blocked by #76.
- Blocked by #88.
- Blocked by #89.
- Blocked by #91.
- Blocked by #92.
- Blocked by #93.

### CODE REVIEW

**Comment by greatislander** [comment]
@erictheise an issue I'm running into: once I get to the end of creating organization, I get this error instead of a successful redirect to the profile:

```
Reverse for 'organization-detail' with keyword arguments '{'organization_id': 1676}' not found. 2 pattern(s) tried: ['api/organizations/(?P<pk>[^/.]+)\\.(?P<format>[a-z0-9]+)/?$', 'api/organizations/(?P<pk>[^/.]+)/$']
```

The OrganizationProfileWizard ends like this:

https://github.com/platform-coop-toolkit/coop-map-directory-index/blob/add/organization-flow/maps/views.py#L158

I'm not clear on why this would be happening as the redirect pattern looks correct to me. If you have any insight, it would be greatly appreciated.

**Comment by greatislander** [comment]
This is ready for review now, @erictheise. It includes a lot of changes. As I'm a newbie when it comes to Django/`django-formtools`, I'm eager to get your feedback on any best practices I'm not following.

**Comment by greatislander** [comment]
@waharnum If you have a chance to test this out that would be great too.

**Comment by greatislander** [comment]
TODO: Update Type/Category selection flow for organizations following #96.

**Comment by erictheise** [comment]
I'll review this tonight @greatislander. Do you anticipate more updates?

**Comment by greatislander** [comment]
@erictheise Nope, I'm as done as can be. I'm turning my attention to the profile pages themselves now. Many thanks!

**Comment by erictheise** [comment]
Without choosing a`type` I am able to continue.image

**Comment by erictheise** [comment]
`State or province` should probably not be required as the equivalent does not exist in all regional addressing schemes. Additionally, the label or helptext should ask the profile creator to spell out the value if it applies, e.g., "California" is preferred to "CA", disambiguating "California" vs. "Canada" and yielding better a better initial geocode.

There are a handful of Python and Django libraries designed to assist with this.

image

**Comment by erictheise** [comment]
At Step 4 there are formatting problems.

Again, I recall that Sectors used to reveal more than one value. Perhaps the number of Sectors is small enough to allow a multi-column presentation of checkboxes.

The worker fields seem scrambled and no radio buttons or checkboxes appear for `distribution`.

image

**Comment by erictheise** [comment]
Step 5. We should talk about helptext or using JavaScript to set placeholders for the Social media fields as I envisioned them. Or another strategy entirely.

**Comment by erictheise** [comment]
Huh. I wasn't expecting that I'd be able to save my entry but the `type` seems to have defaulted to `Shared platform` and the `sector` to `Advertising & Marketing`. The street address doesn't appear in the profile (perhaps by design) and a few things appear as `Unknown` even though I wasn't prompted for them (Dev Stage, Legal Status). I know you're moving on to designing profile pages so it's possible these fields are no longer part of the data model.

image

**Comment by erictheise** [comment]
I recognize that these terms are problematic but my comments are from a user perspective, i.e., black box testing. Perhaps I'm missing some interface components, let me know. Otherwise I'll post internal, i.e., white box, observations in the morning.

**Comment by greatislander** [comment]
Hi @erictheise, I realize I neglected to include this in the testing instructions but the display issues (e.g. missing checkboxes etc) will be resolved by running `npm install` and `npm run build:production`.

**Comment by greatislander** [comment]
Updates from review:

- [x] State / province are no longer required
- [x] Helper text asks users to enter full state / province name rather than abbreviated form

**Comment by greatislander** [comment]
> The street address doesn't appear in the profile (perhaps by design) and a few things appear as `Unknown` even though I wasn't prompted for them (Dev Stage, Legal Status). I know you're moving on to designing profile pages so it's possible these fields are no longer part of the data model.

The profile page design will be adjusted to address some of these issues. Specifically to your points above:

- Full address will be added
- Stage of Development will only be shown for co-ops (because the org you created had ended up with a shared platform type, that field wasn't exposed during the creation flow)
- Legal status and a few other fields are not being collected in the initial creation, but will be part of the prompt to "expand your profile" after it's created.

Apologies again for the missing instructions re: rebuilding CSS and JavaScript. Doing so will fix:

- No checkboxes, radio buttons, or other means of selection appearing at step 1.
- Multiple selects showing only one value.
- The worker fields seem scrambled and no radio buttons or checkboxes appear for distribution.

And probably other things too.

**Comment by erictheise** [comment]
> Hi @erictheise, I realize I neglected to include this in the testing instructions but the display issues (e.g. missing checkboxes etc) will be resolved by running `npm install` and `npm run build:production`.

I suppose I should have known that @greatislander. Add that to the `README`? Also, if this `WARN` is to be expected it should probably be anticipated in the `README` as well:

```
$ npm install
npm WARN browser-sync-webpack-plugin@2.0.1 requires a peer of webpack@^1 || ^2 || ^3 but none is installed. You must install peer dependencies yourself.
```

Finally, `bzip2` is not installed on `demo` so the instructions for getting a database snapshot are no longer current and are probably not the best way to go about it anymore (with multiple users the sql file should probably be dumped into a user's home directory.

**Comment by erictheise** [comment]
@greatislander, after `rm -rf node_modules` and `npm install` I'm getting

```
> coop-map-directory-index@0.1.0 mix /Users/erictheise/Repos/platform-coop-toolkit/coop-map-directory-index
> webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'optimization'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           optimization: ...
         }
       })
     ]
 - configuration.stats should be one of these:
   object { all?, context?, hash?, version?, timings?, performance?, depth?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warnings?, errors?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? } | boolean | "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"
   -> Used by the webpack CLI program to pass stats options.
   Details:
    * configuration.stats has an unknown property 'builtAt'. These properties are valid:
      object { all?, context?, hash?, version?, timings?, performance?, depth?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warnings?, errors?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? }
    * configuration.stats should be a boolean.
    * configuration.stats should be one of these:
      "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"
```

during `npm run build:production`. Is there a better version of npm to use than v12.9.0?

**Comment by greatislander** [comment]
@erictheise can you try unstaging any changes to `package-lock.json` and then run `npm ci`?

**Comment by erictheise** [comment]
I seem to be back in business, thanks @greatislander.

**Comment by greatislander** [comment]
I’ll add that to the reader to. `npm ci` removes `node_modules` and installs exactly what’s specified in the lock file, so is helpful for ensuring that you get the environment to a known working state.

**Comment by erictheise** [comment]
I notice that after I log in and visit __My profiles__ I get two __Success__ messages saying the same thing: _Successfully signed in as erictheise@gmail.com._. Seems I should get only one of these, and earlier in the flow, directly after I sign in.

**Comment by greatislander** [comment]
> I notice that after I log in and visit **My profiles** I get two **Success** messages saying the same thing: _Successfully signed in as [erictheise@gmail.com](mailto:erictheise@gmail.com)._. Seems I should get only one of these, and earlier in the flow, directly after I sign in.

I've noticed this too— I'm going to open a separate issue.

**Comment by erictheise** [comment]
On a related note, there's no __Success__ message when organizational profiles are created.

**Comment by erictheise** [comment]
Brand new organization profiles should be saved with a `source` that probably defaults to `Organic`. I don't know if values of `source` should surface to Users but an admin may want to create new values to go along with new user campaigns, e.g., specific conferences or course offerings.

Adding this is blocked by work I need to do in #102 so I don't know how you'd prefer to keep tabs on this @greatislander.

**Comment by erictheise** [comment]
The spelling _organisation_ is used on the __More about you__ form in the individual flow rather than the American English spelling, _organization_. [Agreed upon style at one point](https://github.com/platform-coop-toolkit/coop-map-directory-index/issues/31#issuecomment-620700450) was American English.

**Comment by erictheise** [comment]
I deleted the individual profile I set up back at the beginning of the project and created a new one. I only added one social media but the profile page that appears at the end held on to earlier ones.

Looks like a problem with cascading database deletes and it's doubtful that this pull request introduced the problem so I will open a new bug issue for that.

**Comment by erictheise** [comment]
Happy to approve this once occurrences of _organisation_ are removed from templates.

Great job @greatislander.

**Comment by greatislander** [comment]
@erictheise I've made that change. Let's get this merged, and then perhaps we can add the `Source` saving (https://github.com/platform-coop-toolkit/coop-map-directory-index/pull/84#issuecomment-647702391) in addressing #102?

**Pull request merged**
